name: pupedia_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - Images/

  fonts:
    - family: Bubblegum Sans
      fonts:
        - asset: fonts/BubblegumSans-Regular.ttf
          weight: 700

    - family: PT Serif Caption
      fonts:
        - asset: fonts/PTSerifCaption-Regular.ttf
          weight: 700


